function createQUTNOISESREfiles(cleanlistfile, noisylistfile, cleanfolder, outfolder)
%
% CREATEQUTNOISESREFILES recreates a list of QUT-NOISE-SRE files
%
%    CREATEQUTNOISESREFILES(cleanlistfile, noisylistfile, cleanfolder, 
%      outfolder) creates  all files listed in 'noisylistfile' into 
%      'outfolder'. 'cleanfolder' should be the root location of the 
%      source of clean audio.
%
% EXAMPLE:
%    % if you want to recreate the testing data listed in
%    % QUT-NOISE-NIST2008.test.short3.list from the clean files listed
%    % in NIST2008.test.short3.list, and your NIST2008 data is stored in
%    % /work/SAIVT/NIST2008, then you can run the following command:
%    createQUTNOISESREfiles('NIST2008.test.short3.list', ...
%                           'QUT-NOISE-NIST2008.test.short3.list', ...
%                           '/work/SAIVT/NIST2008', ...
%                           '../QUT-NOISE-NIST2008')
%    
%    % and similarly for the training data:
%    createQUTNOISESREfiles('NIST2008.train.short2.list', ...
%                           'QUT-NOISE-NIST2008.train.short2.list', ...
%                           '/work/SAIVT/NIST2008', ...
%                           '../QUT-NOISE-NIST2008')
batchaddnoisetospeech('../QUT-NOISE', '../QUT-NOISE/labels', '../QUT-NOISE/impulses', ...
		      cleanfolder, gettxt(cleanlistfile), ...
		      'activlev', ...
		      outfolder, ...
		      8e3, gettxt(noisylistfile), ...
		      'recreate') 
